CC = gcc
CPP = g++
FLEX = flex
BISON = bison

BUILD_DIR = $(ROOT)/build

INC_DIR = $(ROOT)/src/include
CFLAGS = -Wall -pedantic -I$(INC_DIR)
LDFLAGS = -lz3
DEBUG_ON = -D DEBUG_MODE

TARGET = cAnalyzer
TARGET_OBJS = parser.o lexer.o


$(BUILD_DIR)/%.o : %.c
	$(COLOR_RED)
	$(CC) -c $< $(CFLAGS) -o $(BUILD_DIR)/$*.o
	$(COLOR_END)

UNAME = $(shell uname)

COLOR_ESCAPE = \e
ifeq ($(UNAME),Darwin)
COLOR_ESCAPE = \x1b
endif

RED_ON = $(COLOR_ESCAPE)[0;31m
GREEN_ON = $(COLOR_ESCAPE)[0;32m
YELLOW_ON = $(COLOR_ESCAPE)[0;33m
BLUE_ON = $(COLOR_ESCAPE)[0;34m
COLOR_OFF = $(COLOR_ESCAPE)[m


COLOR_RED = @echo -n "$(RED_ON)"
COLOR_YELLOW  = @echo -e -n "$(YELLOW_ON)"
COLOR_GREEN = @echo -e -n "$(GREEN_ON)"
COLOR_END = @echo -e -n "$(COLOR_OFF)"
